### ISSUE TITLE
CordsHandler Client Must Be Supplied

### ISSUE THREAD

**Issue by Adebowale35** [FreakDeveloper/cords-handler#1]
I'm having CordsHandler Client Must Be Supplied. error how to fix this?

**Comment by FreakDeveloper** [comment]
Hello Dear Adebowale,
You Should Add The Cords Handler Client After The Discord.js Client At The Parameter Part. You Can Check The NPM Page!

We wish you a happy,healthy and peaceful new year with your family. - Cords Handler Development Team.

**Comment by Adebowale35** [comment]
I did, Thanks
